/* Generated by tools/gift-encoder.html — don't edit by hand.
   Each entry is [code hash, scrambled gift]. Regenerate to change codes.
   ⚠️ PLACEHOLDER codes right now: CODE1, CODE2, CODE3, CODE4 — replace before gifting! */
window.GIFTS = [
  [
    "384acd0b66b142f1",
    "OEznz8IXOlwBRIoFAs1pWhEwE//4T3lMbD8M/rVGCkYLIAPv6H1QMXYvNB2lJkQ5fRdwXl8+VyF5T2hQVzFzIyNaKgsDWjNKk0dOeg5QbkaAPks9KA1gQYZmSyQsBYxOhmACC21+knD8cjhH"
  ],
  [
    "abe8c03e5a5aca8b",
    "OEznz8EXOlwBRIoFMuRpWhEwE//7T3lMZjce6f4MVQEDJQf77TVSN3U1eFakJl85YUdwSFw+TG5yWT9KFylsJ3pdYgEPT2FH20caKg9QaFPTcVRyK14hUw=="
  ],
  [
    "a5032ad7d49bec89",
    "OEznz8AXOlwBRIoFDcFpWhEwE//6T3lMbzMZ4bcBXgVMPECurS5HMWk/eEClJkQ7dko6GxEqAyhkRGoeHyA7NXNPIQdPSntbiUMaIwhAK0GcbFlyMF8jXZ9jTjN3TZpUh2tRNm1g"
  ],
  [
    "c876c0cb3e5087dd",
    "OEznz98XOlwBRIoFO8ppWhEwE//FT3lMaSQL6f0JXhIBYkDx5DJBJzl8eAnnOE4ie1c8FaA5TG58UysYVGV1KXcOKBcDSTNWlEpeeBU="
  ]
];
